#!/bin/sh

set -e

DEFAULT_BRANCH=$(git default)

NEW_BRANCH_NAME=$(echo $* | awk '{gsub(/[^a-zA-Z0-9_]/, "-", $0); print tolower($0)}')

git stash save --include-untracked Autostashing

git checkout $DEFAULT_BRANCH
git pull origin $DEFAULT_BRANCH
git checkout -b $NEW_BRANCH_NAME $DEFAULT_BRANCH
